### ISSUE TITLE
How will this affect contractors?

### ISSUE THREAD

**Issue by aggieben** [deptofdefense/code.mil#11]
As a former employee of a rather large defense contractor, I'm aware that quite a lot of DoD's procurements are done through a commercial bidding process, and that much of the technology that DoD has rights to is created by non-DoD personnel and businesses rather than directly by DoD personnel.

What, if any, affect would this licensing effort have on those technologies?  What affect might it have on future RFPs and contracts?

**Comment by shawoods** [comment]
This initiative and the draft agreement will not have any direct effect on contractors. The projects we are intending to open source have been developed exclusively by Government employees. The mechanisms for open sourcing code written by Government employees versus code written by contractors on behalf of the Government are very different. You are correct that much of the code written for DoD is written by contractors, but that's a different problem set than what we are tackling right now -- which is code written by Government employees.

**Comment by bill-studer-dhs** [comment]
This seems like a solution looking for a problem. 

Who in the US Federal government besides USDS and 18F employs software engineers writing code?

Furthermore, there are dozens of projects already on GitHub, written for the DOD / IC, that are already released under various open source licenses.

**Comment by tomberek** [comment]
@bill-studer-dhs There are a surprising number of Federal employees who write code or manage projects (even if the primary contributors are contractors). Historically we have found that they face steep barriers in open sourcing. A handful have been able to use various mechanisms to do this, we want to stand on their shoulders and make it even easier. Often the barriers are when management simply says no because they don't understand and don't want to do something "experimental". Sadly, the dozens of projects on GitHub are seen as experimental and as special cases, rather than the norm.

Closing as answered. Feel free to re-open to continue.
