### ISSUE TITLE
What does this mean for software.forge.mil?

### ISSUE THREAD

**Issue by Tronald** [deptofdefense/code.mil#122]
As far as I understand, software.forge.mil is the current platform for DoD opensource development. Is code.mil going to replace, or simply be a more "open" alternative to forge.mil?

**Comment by johnmod3** [comment]
forge.mil is meant only for controlled software development (four, ITAR,
etc.) restricted sorts of things.

Current DoD policy is to be open and do development where it makes sense to
occur

-------------------------------------------
John Scott
 240.401.6574
< jms3rd@gmail.com >
http://powdermonkey.blogs.com
@johnmscott

On June 5, 2017 at 12:15:38 PM, Justin Gielski (notifications@github.com)
wrote:

As far as I understand, software.forge.mil is the current platform for DoD
opensource development. Is code.mil going to replace, or simply be a more
"open" alternative to code.mil?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/deptofdefense/code.mil/issues/122>, or mute the thread

**Comment by jordangov** [comment]
I'm not sure that any of us can really answer what will happen to forge.mil, but we do see this as a different effort, if not 100% so. In any case, to close out the issue, we have no direct connection or control over forge.mil and as far as I know it will not be going away or be replaced by code.mil.
