### ISSUE TITLE
Implement probot-stale to aid in Repository management

### ISSUE THREAD

**Issue by jbjonesjr** [deptofdefense/code.mil#124]
[`probot-stale`](https://probot.github.io/apps/stale/), a [probot](https://probot.github.io/)-app, is used to help manage repositories that don't have day to day interaction. From it's website:

> Automatically close stale Issues and Pull Requests that tend to accumulate during a project.

This will automate some of the `work` that @jordangov is having to do now (ex: https://github.com/deptofdefense/code.mil/issues/112#issuecomment-326099287).

**Comment by jordangov** [comment]
:joy: That's a good little bot. That said, I doubt this code.mil repo will accumulate that much traffic (we only have 14 open issues with this one right now).

Thoughts from others?

**Comment by jordangov** [comment]
In thinking more about this, we're going to hold off on it. Mostly because closing an issue automatically in the Federal Government could be unintentional at the speed we tend to move at (unfortunately). That said, we need to do a better job at issue curation, and if we can't then maybe we can revisit this issue.
