### ISSUE TITLE
Probably need to address moral rights

### ISSUE THREAD

**Issue by dosaygo-coder-0** [deptofdefense/code.mil#21]
Moral rights are rights of creators of copyrighted works generally recognized in civil law jurisdictions and, to a lesser extent, in some common law jurisdictions. They include the right of attribution, the right to have a work published anonymously or pseudonymously, and the right to the integrity of the work.

Moral rights can exist even if the work is in the public domain. 

I don't know if they exist in this case or not.

But it probably works to address what interaction moral rights, if any, make to works created using this license agreement.

**Comment by shawoods** [comment]
@dosaygo-coder-0 This is a super important and tricky area. We'll definitely have to think through this one before we make any changes if any are made. Because our intent is to reuse widely adopted, existing open source licenses, we're not sure we need to do anything special in the agreement. What are your thoughts about that?

**Comment by marctjones** [comment]
The CC0 actually addresses moral rights. So perhaps you can draw some inspiration form there. But that will always be a tricky problem since in some jurisdictions there are limitations on a creator's ability to waiver or relinquish the creator's  moral rights. In other words at some point you just have to say, "yup that person still retains their moral rights in that particular country and there is nothing that can be done to modify or release them." 

A typical formulation in a assignment clause of a contract is to start by saying "I assign everything I legally can; but for what I can not assign, I grant a unrestricted license for, and for what I can not assign or license, I waive my ability to exercise them." 

Perhaps the biggest problem with the CC0 and other creative commons licenses is that the website does not encourage people actually read the [legal code.](https://creativecommons.org/publicdomain/zero/1.0/legalcode) Which is too bad since they are were well designed and readable licenses. The legal code is very different then the simplified [summary](https://creativecommons.org/publicdomain/zero/1.0/) that most people are directed to read.

Of course the great strength of the CC is that they don't force everyone to read their licenses and provide summaries instead. So damned if you do, damned if you don't.

**Comment by dosaygo-coder-0** [comment]
@shawoods I checked GPL v 3 and MIT licenses and they do not mention moral rights which does not mean these licenses fail to have some bearing on moral rights as normally used. 

My thinking is that because in some cases the works of code.mil do not have copyright protections therefore even tho other licenses may normally make regard to moral rights when used with works that *do* have copyright protection, the effects of these licenses may be somewhat changed in this case because the code.mil situation is different, notwithstanding the attempts of the agreement in its current form to bridge that.

@marctjones assignment example seems like a solution albeit one I'm hesitant to endorse because it seems there is more to clarify about how moral rights apply ( or even if it's important to consider it an issue ) before any more clauses are added anywhere. And also because I dislike catch-all clauses and assign-everything clauses because I feel a contract with them is giving me a poor deal with few protections. 

Even tho I fear it's not that useful, I suggest it's time to *call the lawyers* ( whoever they are in this case ). 

My other ( completely legally uninformed ) suggestion is to insert a clause that asserts *some* moral rights but clearly restricts how far it can be taken. Like: 

>[[ in the case where [[ whatever cases this would apply ]],]] this agreement grants you the moral right to assert [[ you made ]] your contribution, but not to restrict [[ the production of ]] derivative works, nor to compel anyone to attribute [[ any part of ]] the work to you.

a change to which the same precaution, to know more about the interaction of moral rights in this context before adding more clauses, applies.

**Comment by BrandonBouier** [comment]
@dosaygo-coder-0 I'm curious: would the DCO attribution to your contribution be sufficient to stand as a moral rights attribution?

**Comment by dosaygo-coder-0** [comment]
@BrandonBouier what's DCO attribution? This sounds like a legal question and I don't know.

**Comment by marctjones** [comment]
@dosaygo-coder-0 to be clear. Moral rights arise as a creation of statutory law. They are not and can not be created via contract or a license. 

The U.S. does grant a limited form of moral rights in some forms of copyrightable material, but not in software. It is my understanding that moral rights in EU countries do not typically apply to software, but I think that is generally a open question since it is hard for anyone to completely understand every countries legal system at that level of detail and then offer a authoritative answer. 

Moral rights are a restricted set of rights that grant the author (not the copyright holder) specific privileges. The challenge with moral rights is not typically how to create them since they can only be created by statute; the challenge is that it is not always clear if or to what extent an author can assign, waive or reliquish them in a contract or license. And it varies widely from country to country.

 That inability to direct how moral rights will or not be used in a predictable manner  freaks out lawyers (and developers) because it leaves a aspect of the relationship between the author and downstream users undefined and potentially subject to the original author's later whims.

You typically see [moral rights](https://en.m.wikipedia.org/wiki/Moral_rights) as a right of attribution or a right of integrity. 

In the context of FOSS moral rights are a concern, because an author could potentially exercise the rights in a way interrupts how people had been using the author's work until that moment. And then everyone with a copy of the work would have to figure out how to comply in response. Or in the case of the right of integrity they might always be some doubt about your ability to modify another person's code which of course is a cornerstone of FOSS. 

Perhaps someone else with a better handle on moral rights can correct any mistakes I may have made, but I think that is a rough overview of moral rights as it applies to this space.

**Comment by marctjones** [comment]
@shawoods probably best to punt on moral rights and let the license you choose speak to (or not as the case may be) them. Otherwise you are back to drafting your own license again.

**Comment by BrandonBouier** [comment]
@marctjones I have to say, I'm enjoying reading your comments :)

@dosaygo-coder-0 DCO stands for [Developer Certificate of Origin](https://developercertificate.org/).

Like you, I'm not sure the moral rights issue can be suitably addressed with what we're trying to do here (beyond the DCO attribution), without adding yet-another-license to the pool (something we've been trying really hard to avoid).

**Comment by dosaygo-coder-0** [comment]
@marctjones thanks for contributing that explanation. And I think your suggestion of just leaving it up in the air is what they were originally intending based on @shawoods first response. 

Based on what you've said it seems to me that if moral rights are these things which can't be granted by contracts, but only by the pre-existing statutes that exist in jurisdictions, and also then if what "moral rights" means could possibly be different everywhere, the only effective thing to do ( unfortunately from my point of view of wanting to lock it down ) -- is to do nothing. 

Unless a lawyer who knows this stuff can weigh in and say "oh there's this solution that you can try" -- if there's no effective way to add a clause to make it clearer - then I reckon it's better to not add anything. And just forget about it. I guess it ( clarifying the interaction with moral rights ) falls outside the scope of this agreement if it is generally a thing which is outside the scope of contracts and also just a pretty hard thing to do anyway.

I mean you could always say -- "Disclaimer: We don't know how moral rights may or may not affect these agreements in the US or other countries." but what would be the point? Because it doesn't really contribute anything tangible, beside notification, which may or may not be important.

Disappointing because I thought this would lead somewhere constructive.

**Comment by marctjones** [comment]
@dosaygo-coder-0 Lead somewhere constructive? I think that was your mistake. ;) See this [t-shirt](https://teespring.com/shop/tlaw#pid=2&cid=2397&sid=back). 

But I am glad my comments were disappointingly helpful. As a new englander I like cloudy days.

**Comment by marctjones** [comment]
@shawoods I am guessing you could close this issue as well.

**Comment by royfielding** [comment]
Open source licenses do not address moral rights because those rights do not restrict modification and distribution of the work. What they restrict is misleading statements about its authorship and overbearing restrictions on the original author; neither is something we would want to license, so they never appear as a licensed permission.

**Comment by shawoods** [comment]
@dosaygo-coder-0 At this time, we don't intend to address moral rights separately. Relative to author attribution, which is different but related, we will comply with whatever open source license is associated with the project. 

Can I close this issue or is something still outstanding from your perspective?

**Comment by dosaygo-coder-0** [comment]
@shawoods I think this is all clear now. Close at will! And thanks for asking first.

**Comment by shawoods** [comment]
Issue resolved!
