### ISSUE TITLE
How does this interact with tech transfer law?

### ISSUE THREAD

**Issue by 2grep** [deptofdefense/code.mil#30]
Glad to see this starting! One issue to add to the list: there's a huge amount of law around technology transfer out of the government, with a big chunk of it being around Cooperative Research and Development Agreements. The standard is that the USG gets a world-wide non-exclusive license to any work product that results from a CRADA. I'm in Navy Medicine, and have several executed CRADAs. Here's the section of US Code: [15USC3710a](https://www.law.cornell.edu/uscode/text/15/3710a). Will I be able to apply this license?

**Comment by tomberek** [comment]
If that is the underlying LICENSE that a project wishes to use, it seems this agreement could be used to facilitate such a license. We explicitly do not want to preordain the license choses and are attempting to allow project managers to tailor their choice of license to the specifics of their projects.

**Comment by BrandonBouier** [comment]
We've pivoted based on user feedback. Take a look at the current CONTRIBUTING.md

**Comment by fulldecent** [comment]
This issue IS still relevant based on the new CONTRIBUTING file.

**Comment by BrandonBouier** [comment]
@fulldecent I believe you're right, that's why I haven't closed this issue.

**Comment by shawoods** [comment]
@2grep Tech transfer law is a special use case we're not tackling yet, but in later iterations we intend to dive into it.  I will keep this open and revisit this issue when we've tackled tech transfer in earnest. Our hope would be that this open source strategy would be helpful for tech transfer scenarios (like under a CRADA) as well, but it may be that we need to make some tweaks or add some FAQs to address those particular circumstances. Certainly any ideas you have would be welcome. I actually just ran into someone at ONR yesterday with similar questions and hopes that this strategy might facilitate tech transfer for software.

**Comment by johnmod3** [comment]
@shawoods as a general question: after there is a solid draft will be it have to go through DoD coordination or DoD Legal office review?

**Comment by shawoods** [comment]
@johnmod3 I am glad you asked because my sense is that some of the Government folks are a little nervous about this experiment. 

As previously stated on several other threads, we are not setting DoD policy with this initiative; rather, we are experimenting on how to foster more collaboration with the open source community on DoD projects. This matters for many reasons, but one of the reasons is that the coordination we are required to have is different than if we were setting policy. CONTRIBUTING.md does not need to go through any additional DoD coordination to finalize it. By the end of March, we hope to finalize our strategy and open source some Defense Digital Service (DDS) projects. And then we'll see what happens!

FYI, we have been collaborating with various attorneys, including, but not limited to, ones in DoD. I am the DoD attorney for the Defense Digital Service. Explaining who we've talked to is something we plan to add to the FAQ.

There is a lot we can do within existing Federal guidance and law. We will continue iterating and advancing in small steps. We will continue to actively seek community feedback. Depending on where this goes, it may require a different kind of DoD coordination, legal or otherwise. We'll cross each bridge as we get to it!
