### ISSUE TITLE
Consider using CC0 for this project

### ISSUE THREAD

**Issue by fulldecent** [deptofdefense/code.mil#37]
The goal of this license as it stands is:

* Allow the US Military to publish things
* Confirm that US copyright does not apply
* Denounce any foreign copyright if it exists
* Require positive identification of new contributions

There is already an existing license that achieves this, has been thoroughly reviewed, and enjoys widespread adoption. Namely, the [CC0 license](https://creativecommons.org/publicdomain/zero/1.0/legalcode).

**Additionally, the CC0 makes many disclaimers about the published material so as to limit liabilities that the publisher assumes by making publication. Specifically, this addresses issue #36.**

Note: CC0 does NOT satisfy the current requirement of DOSA 1.0draft in using a Developer’s Certificate of Origin. No problem. Instead, this requirement should be discussed in CONTRIBUTORS.md.

**Comment by Artoria2e5** [comment]
Public Domain licenses are great, and CC0 might be the best one I know of. Still, [OSI's Review Committee's](https://opensource.org/faq#cc-zero) reason for not approving CC0 (yet) may be worth looking into and addressing:

> CC0 was not explicitly rejected, but the License Review Committee was unable to reach consensus that it should be approved, and Creative Commons eventually withdrew the application. The most serious of the concerns raised had to do with the effects of clause 4(a), which reads: "*No ... patent rights held by Affirmer are waived, abandoned, surrendered, licensed or otherwise affected by this document.*". While many open source licenses simply do not mention patents, it is exceedingly rare for open source licenses to explicitly disclaim any conveyance of patent rights, and the Committee felt that approving such a license would set a dangerous precedent, and possibly even weaken patent infringement defenses available to users of software released under CC0.

(lloydde from Hacker News [posted such a quote there](https://news.ycombinator.com/item?id=13728332). I was just following the link.)

**Comment by tomberek** [comment]
We have looked at and considered CC0. See [FAQ](https://github.com/deptofdefense/code.mil/blob/master/FAQ.md#since-software-created-by-us-federal-government-employees-does-not-have-copyright-protections-in-the-us-why-not-just-put-it-in-the-public-domain-and-use-cc0-10-for-international-jurisdictions-where-you-have-copyright).

We are not proposing that CC0 is incorrect or trying to set a policy. We are exploring a different approach. It may work, it may not. Rather than specifying the license that DoD project should use, we wanted to create a framework where the individual project owner could choose the appropriate license for themselves.

The suggestion to move contribution details into CONTRIBUTIONS.md is valid and we will get to that shortly. There is also an alternate suggestion at #33,#34 that may be closer to what you are suggesting.

Closing as addressed in FAQ.
