### ISSUE TITLE
Please explain Plan/Intent more clearly in Readme

### ISSUE THREAD

**Issue by storrgie** [deptofdefense/code.mil#41]
In your [FAQ](https://github.com/deptofdefense/code.mil/blob/master/FAQ.md#is-dod-trying-to-do-something-funny-here) you specifically call out 'Is the DoD trying to do something funny here'. Yet, in your README you make reference to the 'end of March' twice without explaining what the plan is for the solicitation.

So despite the 'is the DoD trying to do something funny' and the immediate 'no', you literally have a literal hidden agenda. Not likely nefarious, but it would be nice to see some more clear intent on timeline and expected results. You could even state that you've chosen that timeline arbitrarily as an incentive for people to participate, just an explanation would be meaningful.

So here are some of my questions I'd like to see addressed in the README:

 - The results of this solicitation for feedback are intended to be briefed at what level (e.g. DDS internally, some IPT within the Pentagon, someone from OSD whos become interested in Open source?)
 - Have you staffed this project with legal council? We can all look at the https://www.dds.mil/ site and see the team, but despite the titles do you have some lawyers working on this. One could surmise that @shawoods would be it, but it would be nice for that to be clear. You're going to see a lot of IANL in regards to a topic that very much needs to be discussed by a Lawyer.
 - Have you attempted to broker connection to other efforts within the DoD, have you gotten a response. The most notable would be [ARL Open Campus](https://www.arl.army.mil/opencampus/), specifically their draft document for releasing software in an unrestricted public fashion. This should be a Lawyer to Lawyer discussion, as it appears ARL has staffed their effort with council and has been working on this since 2015 (and likely earlier).
 - Why do you specifically request sign off? This seems like an arbitrary barrier to entry that is unconventional to other projects. You could make a blanket statement about what it means to do a pull request, and what , but sign off seems confusing and not value added.

**Comment by jbjonesjr** [comment]
@storrgie for reference, I'd argue that some of your questions above may be best answered as additions to the FAQ instead of the README.

Additionally, I've found that having deadlines and targets helps to ensure that everyone involved in a community (either implicitly or explicitly) have the opportunity to participate and be heard. I appreciate the acknowledgment of a schedule.

**Comment by BrandonBouier** [comment]
We've pivoted based on user feedback. Take a look at the current CONTRIBUTING.md

**Comment by fulldecent** [comment]
These comments are meta- in terms of this project and its purpose. Therefore it is not affected by the pivot in CONTRIBUTING.

**Comment by ckaran** [comment]
@jbjonesjr If you start putting deadlines on public comments, you may be wandering into areas governed by the [APA](https://www.archives.gov/federal-register/laws/administrative-procedure) and other laws.  I'm not a lawyer, so I can't make a definite comment; please consult your legal counsel about this.

**Comment by shawoods** [comment]
The FAQ has been substantially updated since this issue was started. @storrgie please see below. Before I close this issue, is anything else outstanding from your perspective?

>The results of this solicitation for feedback are intended to be briefed at what level (e.g. DDS internally, some IPT within the Pentagon, someone from OSD whos become interested in Open source?)

See https://github.com/deptofdefense/code.mil/blob/master/FAQ.md#who-is-behind-codemil
This isn't being "briefed" at any particular level. Code.mil is an experiment in open source at the U.S. Department of Defense (DoD) being led by DDS. The goal is to foster open collaboration with the developer community across the world on DoD open source projects.

>Have you staffed this project with legal council? We can all look at the https://www.dds.mil/ site and see the team, but despite the titles do you have some lawyers working on this. One could surmise that @shawoods would be it, but it would be nice for that to be clear. You're going to see a lot of IANL in regards to a topic that very much needs to be discussed by a Lawyer.

Yes, I am a lawyer. Yes, we have talked to many, many lawyers and continue to do so. See https://github.com/deptofdefense/code.mil/blob/master/FAQ.md#who-has-been-involved-with-codemil

>Have you attempted to broker connection to other efforts within the DoD, have you gotten a response. The most notable would be ARL Open Campus, specifically their draft document for releasing software in an unrestricted public fashion. This should be a Lawyer to Lawyer discussion, as it appears ARL has staffed their effort with council and has been working on this since 2015 (and likely earlier).

Yes, we have talked to ARL. We have also talked to the folks at Code.gov. Yes, we have reached out to other Government offices interested in open source. Once DDS releases a few projects in Code.mil, we intend to do more extensive outreach in hopes of identifying other DoD offices with projects they might like to open source on Code.mil.

>Why do you specifically request sign off? This seems like an arbitrary barrier to entry that is unconventional to other projects. You could make a blanket statement about what it means to do a pull request, and what , but sign off seems confusing and not value added.

See https://github.com/deptofdefense/code.mil/blob/master/FAQ.md#how-are-you-handling-code-contributions

Some kind of contributor signature is necessary to ensure the project maintainer has secured an irrevocable license to use the contribution. 

I hope this helps!
