### ISSUE TITLE
Consider renaming upstream organization

### ISSUE THREAD

**Issue by storrgie** [deptofdefense/code.mil#43]
If you've secured the ability to use the name "Department of Defense" then please announce how that was secured. I would then promptly request to be a member of this organization and start my own projects as I am a member of the DoD.

Otherwise you should have the upstream organization that owns this project be named "Defense Digital Service".

**Comment by tomberek** [comment]
@storrgie : That is the long-term plan. At the moment we have not found the organization that is willing to manage the DoD-wide page. In our description we did add "Defense Digital Service" to make this distinction clear.

**Comment by storrgie** [comment]
Now you've fractured this repository into another location just because someone suggested that mercurial might be interesting to use as well? (#54).

Do you guys have a plan for the overall "branding" of using the DoD name, or is this a "yolo" type thing where you hope someone will swoop in and tell you how to manage one of the largest organizations in the world online identities.

**Comment by enckse** [comment]
another thing about "branding" and "plan" - if this is backlog doesn't seem like it should be closed especially since it would be a part of the "long-term" plan to clarify intent entirely.

**Comment by tomberek** [comment]
This repo is specifically for discussion and development of a framework/license/agreement to encourage open source in DoD. While perhaps convenient, this repo is not the proper place for the branding question and plan for the organization identity. Please reach out to us to discuss those topics separately because there is definitely a need for it.

**Comment by enckse** [comment]
I will let this one go but I need to add some final notes first.

> While perhaps convenient, this repo is not the proper place for the branding question and plan for the organization identity.

I disagree. This repo is already applying a branding to all of what is being done and broadly covering the DoD community by naming alone (regardless of intent). Perhaps you only wanted non-DoD community input (which is dismissive of some of your users, people like me). Let's be honest, once you step out into "deptofdefense" on github and have references/links (no matter how trivial/minor) for something like code.mil...you've committed to that. If you are representing all of the DoD then why is there so much noise in something like issue #8 being questioned? Regardless of intent or plan "deptofdefense" == DoD on github now...if this fizzles out it becomes squatting on the organizational name.

> Please reach out to us to discuss those topics separately because there is definitely a need for it.

I don't understand this request (I understand the words, not the intent). Again, per #8:

> Rather than concocting some scheme behind closed doors, we shared our ideas and readily sought the feedback of the open source and free software communities.

If you wanted to have this conversation it could've been had. I don't think myself, or some of the other more aggressive comments from other DoD members are strictly saying "Why wasn't I **personally** consulted?!?!", I have a very thorough understanding of being in the trenches (being just another person) where I am trying to do my research day-to-day (which is not about software licensing, contracts, etc.) and in my free time (which I do not have, since I have research to do) fighting the DoD/organization to be respectful of what I can do in the domain of software, engineering, and comp sci. However, that does mean, though that I am aware of when things like this are being discussed internally or at least there are rumblings of a happening at the first I heard of this was the hackernews post and "tada"

This very much feels like @storrgie declaring this a "yolo" event, which is disappointing...some organizations barely consider software engineering a real competency (like mine) let alone seeing this and knowing now that I'm going to be shackled to things I generally may **strongly** disagree with and find disappointing to have to deal with because the "deptofdefense" organization on github is a thing now.

**Comment by storrgie** [comment]
I'd motion this should not be considered closed or resolved. Please re-open or migrated the repository to a DDS organization rather than a DoD one.

**Comment by zacsketches** [comment]
I'd like to concur with @storrgie here.  The professionalism with which you represent DoD matters a great deal.  There are many of us that are working hard to build open and transparent relationships with the software development community.  My particular effort on behalf of the Navy was recently covered in Fast Company and yet I would never claim to represent all of DoD because I am just the community advocate for a single service, even if it is the best one (Go Navy!).   Thus, moves like hosting a DoD meetup with only a few hours notice or not articulating the transition plan for this license to a specific R&D program hurts credibility.

**Comment by storrgie** [comment]
@zacsketches thanks for chiming it, I'm glad you found this even though it was closed already.
