### ISSUE TITLE
NASA hack?

### ISSUE THREAD

**Issue by johnmod3** [deptofdefense/code.mil#44]
There was a hack we looked at a while back that could work: if DoD designated NASA as an agent for releasing government employee created works then NASA could release it under any open source license since NASA can create copyright

**Comment by shawoods** [comment]
@johnmod3 What is your legal basis for saying NASA can create copyright? We talked to NASA. Check out https://invention.nasa.gov/evaluation-protection.php and the last Q&A at the bottom. Unless there is a contractor in the mix who assigns copyright, NASA employees do not have copyright in code solely written by them.

**Comment by shawoods** [comment]
Closing for now unless we get new information.

**Comment by johnmod3** [comment]
I did some digging found this: 
'Copyright © 2007-2016 United States Government as represented by the Administrator of the National Aeronautics and Space Administration. All Rights Reserved.'
via https://github.com/nasa/earthdata-search/blob/master/LICENSE
in the NASA github repo - I'm looking for language, but i seem to remember that NASA can create and claim copyright. Other repo's have JPL and contractors with NASA/gov acknowledged. This would seem to indicate that?

**Comment by konklone** [comment]
No, I think NASA is just wrong. Government agencies do this all the time. If you pressed them, I think NASA would take the notice off.

**Comment by scottg** [comment]
Bottom Line: The US Government (USG) can hold copyrights, and in most cases can trigger copyrights to be created as side-effect of work done by mix of contractors and federal employees, and those copyrights can then be assigned to the USG. The Copyright Act of 1976 governs this issue.

What this means in practice from my experience:

- Anything created by a federal employee as part of their job cannot be copyrighted by the USG within the US (outside the US, the USG can create and hold copyright in that work). 

- Anything created by a contractor on behalf of the USG _can_ be copyrighted and 'owned' by the USG, regardless of how many federal employees contributed to that work (though if you can identify the exact portions using diffs or whatever and know which parts were truly written by those federal employees, you can extract those portions as those would not be covered by copyright.)

- Any entity can _assign_ the copyright to some body of work (if they own that copyright) to the USG, and the USG can _hold_ that copyright, it just can't create copyright in works solely created with federal employees.  

- If a federal employee writes software using their personal time and materials, that individual _can_ copyright that work because it is theirs, is not part of their job and wasn't created at work (e.g. if I write a novel on my time and with my materials, it belongs to me and is not in the public domain just because I happen to be a federal employee).

If you want to create copyrights in works created by the USG in a wholesale fashion across any part of the USG, here's the strategy I would probably suggest: have GSA or other willing Agency create a contract with a commercial organization and then create task orders where that contractor is given the responsibility for creating the initial 'hello world' code and repository for a new project that an Agency wants to start, have the company copyright it and assign the copyright to the USG as represented by whatever Agency wants it, and then bring in as many Federal employees you want to work on it.

Attached is a good analysis of the issue that came out about 5 years after the Act was signed into law.

[Copyright in Government Employee Authored Works.pdf](https://github.com/deptofdefense/code.mil/files/814494/Copyright.in.Government.Employee.Authored.Works.pdf)

/s.
