### ISSUE TITLE
Why not Public Domain?

### ISSUE THREAD

**Issue by impredicative** [deptofdefense/code.mil#52]
What is all this licensing, copyright and contractual nonsense? Isn't federal work supposed to be in the public domain? No other license need be attached or considered.

**Comment by oddnoc** [comment]
This was my immediate reaction as well. Most government intellectual property is automatically in the public domain. By definition, if there is no copyright, there can be no license; to put it another way, DoD has no power to license the code, as it is *already* in the public domain.

Not even [CC0](https://creativecommons.org/share-your-work/public-domain/) is appropriate, as that is a waiver of copyright, which right does not exist in the code proposed to be released.

I am not a lawyer, just an informed citizen.

**Comment by MorrisR2** [comment]
Many countries, and international treaties, have no concept of "public domain".   Therefore public domain won't work if any users are outside the US.

On the other hand, a license similar to the WTFpl would solve the need for a license, without putting any restrictions on the code.

**Comment by FOSS-the-world** [comment]
@MorrisR2 Oh really! I wonder if mine has!

**Comment by impredicative** [comment]
@MorrisR2 , I acknowledge, but to the best of my knowledge, the US federal government cannot legally assign a license or copyright. With regard to those other countries, I suggest petitioning those countries to embrace PD, or have someone in the US clone the relevant repos and simply add a suitable OSS license. Disclaimer: I am not a lawyer.

**Comment by MorrisR2** [comment]
@impredicative Under section 105, the section you have in mind, the government indeed may not *assert* copyright rights (to certain things).  They may certainly *disclaim* such rights; they may point out that there are no restrictions.  For that purpose, the purpose of explicity *not* asserting rights, we can use the Morris Public License:

Morris Public License Version 1.0

1) Authorization to copy, modify, and distribute

Any person, may copy, modify, distribute, or otherwise use the work in any form, without copyright restriction of any kind. All copy rights are hereby disclaimed.

2) Disclamer of warranties
THERE IS NO WARRANTY FOR THE PROGRAM, TO THE EXTENT PERMITTED BY APPLICABLE LAW. EXCEPT WHEN OTHERWISE STATED IN WRITING THE COPYRIGHT HOLDERS AND/OR OTHER PARTIES PROVIDE THE PROGRAM âoeAS ISâ WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.

**Comment by tomberek** [comment]
Please see the FAQ for the response for why this project exists. Changing the global copyright regime, while interesting and ambitious, is out of scope for this project at the moment. We are considering a non-contractual approach (see #33,#34) for which we would appreciate comment.

Closing as answered. Feel free to reopen to continue discussion.
