### ISSUE TITLE
License DOD Code as CC0

### ISSUE THREAD

**Issue by bluefoxicy** [deptofdefense/code.mil#68]
For published DOD code by Federal employees and commissioned by the DOD with copyrights included (i.e. the code is owned by the DOD and thus is under the same non-copyright restrictions as Federal-employee-produced code), use the CC0 license at the below:

https://creativecommons.org/share-your-work/public-domain/cc0/

The CC0 is a legal copyright license including the following clause:

> 2. Waiver. To the greatest extent permitted by, but not in contravention of, applicable law, Affirmer hereby overtly, fully, permanently, irrevocably and unconditionally waives, abandons, and surrenders all of Affirmer's Copyright and Related Rights and associated claims and causes of action, whether now known or unknown (including existing as well as future claims and causes of action), in the Work (i) in all territories worldwide, (ii) for the maximum duration provided by applicable law or treaty (including future time extensions), (iii) in any current or future medium and for any number of copies, and (iv) for any purpose whatsoever, including without limitation commercial, advertising or promotional purposes (the "Waiver"). Affirmer makes the Waiver for the benefit of each member of the public at large and to the detriment of Affirmer's heirs and successors, fully intending that such Waiver shall not be subject to revocation, rescission, cancellation, termination, or any other legal or equitable action to disrupt the quiet enjoyment of the Work by the public as contemplated by Affirmer's express Statement of Purpose.

Essentially the CC0 claims the work is in the Public Domain, which is legally-required of work produced by the Federal government.  The CC0 further claims that, should the Public Domain release be illegal in the recipient's jurisdiction, then the waiver of copyrights is exercised to the maximum legal extent, and an unlimited and unrestricted license to use the work for any purpose is granted.

This license does not conflict with the Public Domain requirement because it fully and permanently waives any copyrights and related rights, of which the Public Domain requirement stipulates the Federal government has none.  You are, in fact, allowed to waive any rights you may or may not have, QED.

**Comment by iadgovuser1** [comment]
Our IP lawyers have already said CC0 (or any license) that says you are a copyright holder and then relinquishing or reassigning said copyright is automatically a no go. U.S. fed civilian code does not have a copyright holder (in most cases). You can still use CC0 to waive copyright outside the U.S. (where public domain is recognized).

See #52, #37, #24. 

https://github.com/deptofdefense/code.mil/blob/master/FAQ.md#since-software-created-by-us-federal-government-employees-does-not-have-copyright-protections-in-the-us-why-not-just-put-it-in-the-public-domain-and-use-cc0-10-for-international-jurisdictions-where-you-have-copyright

**Comment by BrandonBouier** [comment]
@iadgovuser1 well said

**Comment by tomberek** [comment]
Duplicate with #24,#37,#38,#52, and the [FAQ](https://github.com/deptofdefense/code.mil/blob/master/FAQ.md#since-software-created-by-us-federal-government-employees-does-not-have-copyright-protections-in-the-us-why-not-just-put-it-in-the-public-domain-and-use-cc0-10-for-international-jurisdictions-where-you-have-copyright).

To clarify, this effort is an attempt to find an alternate option or path for government projects to join the open source community. 

This project does NOT claim that CC0 is an invalid approach. We'll update FAQ.md to make this a bit more clear. Let us know 

Closing as duplicate.

@iadgovuser1: thanks, i was in the middle of writing this when your response popped up.
