### ISSUE TITLE
License explanation in CONTRIBUTING.md

### ISSUE THREAD

**Issue by shawoods** [deptofdefense/code.mil#81]
With the updated strategy, there is no longer a separate open source agreement. We debated on where in the documentation to put the remaining explanation about how the licensing would work. It is currently in Section 1 of CONTRIBUTING.md. Any thoughts about keeping it there versus breaking it out into a separate file?  If you think we should break it out, what would you recommend we name the file?

**Comment by dosaygo-coder-0** [comment]
I think that's a good idea because now it's more like the terms of contributing, which is more in line with how open source projects order their contribution behaviour. The intended purpose of what you're trying to do seems more clear now that the concepts of the former agreement are expressed in the familiar vehicle of the contributing guideline doc. Seems to have shifted the emphasis from "legally focused" to "developer friendly" which seems like a pretty good thing.

**Comment by marctjones** [comment]
@shawoods I think section 1 is a little confusing it taken literally.

"This Work is not eligible for copyright protection in the United States (U.S.). This is generally understood to mean that this Work is placed in the public domain."

You don't actually mean that as  a unqualified statement do you? I think you mean to say that the government work contained in the project is not eligible for copyright within the united States. But the way it is worded suggests that if a non-governmental contribution was submitted it would not be covered by copyright in the united States.

**Comment by shawoods** [comment]
@marctjones Grrr. Fair point. Working on it.

**Comment by shawoods** [comment]
Just updated the language. Check out the latest file.  What do you think?

**Comment by marctjones** [comment]
@shawoods I think that explanation of what you are trying to do with licensing is much clearer. 

If I can make two stylistic suggestions:

1) It seems it would be clearer to lead your explanation of the licensing status of the code base, not by explaining/acknowledging this quirk of U.S. Government works, but by stating how you want people to treat the code. By asserting copyright in all foreign jurisdictions and licensing the code in those jurisdictions under a particular license, you are essentially forcing even developers in the U.S. treat the code as if it is licensed that way. Otherwise forkers inherit this licensing quirk as well. Rather then bury the solution to the problem, put the solution up front. People never read the last sentence of a paragraph.

Perhaps something like:
> This project is (or should be treated as if it is) licensed under the X license. In countries where copyright protection is available, contributions made by U.S. federal government are available under the X license. The portions of this Work written by United States federal government employees within the scope of their federal employment are not eligible for copyright protection in the U.S.

I think something like that would have the advantage of:
1) It communicates upfront that everyone should treat this project as if it is licensed under X
2) It asserts the copyright of the U.S. government in foreign jurisdictions where it is available.
3) It acknowledges that US Government works are not subject to copyright protections in the United States.
4) It communicates to government employees that only their contributions made within the scope of their federal employment are denied copyright protections within the U.S..

It seems like (4) has a limited audience but it might be important to you. If it isn't you could make that explanation of the licensing status of the code base even shorter.

But in any event it seems like having (1) up front is the best way to describe the licensing status of the project because that is how you want to encourage people in practice to treat it. (Although to be honest I think it is a little weird to release the code in the United States with out any copyright protection but to assert copyrights in other jurisdiction. I am not taking a position on if you can or can not do that. That is for your lawyers to tell you. Just seems odd to me. But as your group has said you are trying something new.)

My second suggest would be to consider removing Section 1 from the CONTRIBUTING file altogether. The way I understand Section 1 is as describing the license of the code base, not about the license of a new contribution to the code base. I might be alone in this, but when I want to know the license of a code base I go to the files that are called LICENSE and COPYING first. If I am thinking about contributing I go to the file called CONTRIBUTING first. I would be frustrated to discover key licensing information was only present in the CONTRIBUTING file.

I think the two files serve different functions and are directed at different audiences. To the extent that the audiences overlap you can could always reference the other file. This way you don't need to duplicate the information in each file and run the risk of having licensing information fall out of sync. 

In addition project policies and licensing status also seem like different creatures to me. So by putting the licensing status in a different file you can also focus each file on its primary purpose. I think a CONTRIBUTING file should describe policy about what is required for a contribution to be accepted and/or describe the process on how to make a contribution.

You might want to check out the [Software Freedom Law Center's advice](http://softwarefreedom.org/resources/2012/ManagingCopyrightInformation.html) on organizing licensing information for ideas about how to organize your LICENSING file. At the very least I think it suggests you have a lot of flexibility in terms of what a LICENSING file looks like. Thier advice is probably more prescriptive then descriptive though.

You might want to look at how other projects use their contributing file. For example the OpenLighting Project does a pretty good job of describing how to [contribute](https://www.openlighting.org/openlightingproject/get-involved/contributing/) to there project. You of course are trying to adopt a very different contribution policy, but I think OLP might be an informative contrast.The only reference to licensing in the contributing material is in the [README.developers](https://raw.githubusercontent.com/OpenLightingProject/ola/master/README.developer) file. And there it talks about how the contribution should be licensed not how the existing code base is licensed. But a potential contributing developer pretty much learns everything he needs to know about contributing by reading that that web page and the referenced README.developer file.

You can see that the OpenLighting Project's [CONTRIBUTING](https://github.com/OpenLightingProject/ola/blob/master/CONTRIBUTING) and [LICENSE](https://github.com/OpenLightingProject/ola/blob/master/LICENCE) files are pretty straight forward and do distinct jobs. The CONTRIBUTING file again references the same README.developer file that includes information about how to new contributions should be licensed. The LICENCE file in contrast describes what the project maintainers believe the licensing status of the existing code base to be. 

Again suggestions from random guys on the Internet should be taken with a grain of salt. This is not legal advice and you should always consult with your attorney. And I am not your attorney. My suggestions here only serve to point out other examples of how people are doing things and the style of doing them. I am not commenting on the legal accuracy of any of the material.

**Comment by royfielding** [comment]
I agree with @marctjones suggestions above. The public domain concept is a special case of golden permission that software recipients never need to worry about, in spite of the hand-wringing within government legal discussions that you are facing right now. Focus should be placed on the intended license for all parts of the work which are not (for the recipient) in the public domain.

**Comment by shawoods** [comment]
@marctjones @royfielding Thank you for this feedback! I agree and updated CONTRIBUTING and LICENSE. Please see PR #103. What do you think? Is this better?  Any suggestions on language?

@royfielding Really appreciate you commenting on this project.

**Comment by marctjones** [comment]
@shawoods I like this current approach. I hope my comments were more useful then distracting. I would close this issue.

In the interest of focus I would suggest if anyone (including myself) has any other suggestions they open a specific issue.

**Comment by shawoods** [comment]
@marctjones Your feedback helped make it better, so no distraction at all! Closing, but if anyone has issues with current language please start a new issue.
