### ISSUE TITLE
Instructions for projects

### ISSUE THREAD

**Issue by tomberek** [deptofdefense/code.mil#91]
Situation: Someone selects ISC for their project. The text from [here](https://opensource.org/licenses/isc-license) is:

> ISC License (ISC)
> Copyright <YEAR> <OWNER>
> 
> Permission to use, copy, modify, and/or distribute this software for any purpose with or without fee is hereby granted, provided that the above copyright notice and this permission notice appear in all copies.
> 
> THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

What should be the recommended content of the Copyright line? The `<YEAR>` is the current year. `<OWNER>` cannot be US Government since we do not ask that contributors assign copyright and federal employees don't have it. There seem to be a few variations in common use: 

> Copyright 2017 Contributors
> Copyright 2017 [PROJECT NAME]
> Copyright 2017 [PROJECT NAME] Contributors
> Copyright 2017 [PROJECT NAME] and other Contributors

What is appropriate to recommend to projects considering our flavor of CONTRIBUTING.md?

**Comment by tomberek** [comment]
Markdown obliterated the following in the original of the ISC:
```
Copyright <YEAR> <OWNER>
```

**Comment by BrandonBouier** [comment]
@tomberek it might be simpler for the project to go with the MIT license instead in this case. From the government standpoint they would be functionally equivalent.

**Comment by tomberek** [comment]
The question is similar for MIT:

```
Copyright <YEAR> <COPYRIGHT HOLDER>
```

**Comment by marctjones** [comment]
@tomberek Wouldn't this be a question for legal counsel since it appears to be about compliance with a statute? I believe others have mentioned before in unrelated issues that it is not considered in appropriate in the FOSS community to have private discussions with legal counsel when seeking legal advice.

It appears @shawoods is an attorney for your group perhaps she can advise you or knows the government attorney who is experienced in the area.

**Comment by dosaygo-coder-0** [comment]
I think it's not necessary to get legal on this because by avoiding assigning copyright to the U.S Government or federal employees you're steering clear of the legal no-no of saying U.S. Government works have copyright. 

And so as long as we're in the legal clear then it's a choice between the options guided by other non-legal reasons and guided by the purpose, which is a recommendation for projects to use.

I'll contribute a perspective that

`Copyright 2017 [PROJECT NAME] Contributors`

is the option that works because, given the following reasons about the other options:

- just `Contributors` leaves off the project which seems too general,
- just the `[PROJECT NAME]` suggests the project is some coherent "entity" in itself, which isn't necessarily the correct focus for some OS project, and
- `other Contributors` suggests that there are a nebulous group of "others" who we don't really know how to specify and yet they somehow deserve separate mention to the "project contributors". This seems unnecessary, too non-specific and not faithful to the actual situation, 

it is really the only option.

**Comment by marctjones** [comment]
@dosaygo-coder-0 The form of a copyright notice is actually pretty specific. While I @tomberek accurately described the form that copyright notices often take in open source projects, The Copyright office publishes [circulars](https://www.copyright.gov/circs/) on various copyright law issues, including one on [copyright notices.](https://www.copyright.gov/circs/circ03.pdf) What the requirements and permitted variations of a statutorily defined copyright notice is. Probably not the whole reference an attorney should look to when giving advice, but for someone seeking to understand the issue for themselves it is probably a good starting point.

The circulars are actually very readable. Anyone one who finds statutes too dense or confusing to read and understand quickly, these are a good alternative when seeking to understand copyright law issues. 

For example here is the copyright office's explnation of how to format a notice on a visually perceptible copies of a work:

>Visually Perceptible Copies
>
> The notice for visually perceptible copies should contain all three elements described below. They should appear together or in close proximity on the copies.
>
> 1 The symbol © (letter C in a circle); the word “Copyright”; or the abbreviation “Copr.”
>
> 2 The year of first publication. If the work is a derivative work or a compilation incorporating previously published material, the year date of first publication of the derivative work or compilation is sufficient. Examples of derivative works are translations or dramatizations; an example of a compilation is an anthology. The year may be omitted when a pictorial, graphic, or sculptural work, with accompanying textual matter, if any, is reproduced in or on greeting cards, postcards, stationery, jewelry, dolls, toys,
or useful articles.
>
> 3 The name of the copyright owner, an abbreviation by which the name can be recognized, or a generally known alternative designation of owner.1 
>
> Example `© 2012 Jane Doe`
>
> The “C in a circle” notice is used only on “visually perceptible” copies. Certain kinds of works, such as musical, dramatic, and literary works, may be fixed not in “copies” but by means of sound in an audiorecording. Since audiorecordings such as audiotapes and phonograph discs are “phonorecords”
and not “copies,” the “C in a circle” notice is not used to indicate protection of the underlying musical, dramatic, or literary work that is recorded.

**Comment by marctjones** [comment]
@dosaygo-coder-0 Just to clarify the [statute](https://www.law.cornell.edu/uscode/text/17/105) that denies a grant of copyright protection in works created by the federal government also makes clear that the federal government can hold copyrights it has been given for some reason. In other words unlike most "people" the federal government doesn't get granted a copyright when it is the original author of a work, but a author who does have copyright in a work can assign those copyrights to the federal government. 

This is a little confusing and you can see by reading the [notes](https://www.law.cornell.edu/uscode/text/17/105?qt-us_code_temp_noupdates=1#qt-us_code_temp_noupdates) for the statute that Congress said at the time it adopted the statute it intentionally left that part fuzzy to give government agencies flexibility.

So its not a "no-no" for the U.S. Government to claim copyright if they do so as a result of the copyrights being assigned to it.

**Comment by tomberek** [comment]
Closing as completed.
